package com.example.tcmherb

class HerbData {
    fun nameZH(index: Int) = herbNameChinese[if(index < 0) 0 else index]

    fun nameEN(index: Int) = herbNameEnglish[if(index < 0) 0 else index]

    private val herbNameChinese = arrayOf(
        "中文名稱",
        "黃苓",
        "熟地黃",
        "黨參",
        "甘草",
        "懷牛膝",
        "麥門冬",
        "白术",
        "野葛",
        "桑白皮",
        "桔梗",
        "山茱萸",
        "何首烏",
        "赤芍",
        "桂皮",
        "岷當歸",
        "川芎",
        "川紅花",
        "枳實",
        "紅棗",
        "細辛根",
        "連翹",
        "懷山藥",
        "款冬花",
        "乾薑",
        "袍附子",
        "桃仁",
        "紫苑",
        "烏藥",
        "銅陵鳳丹皮",
        "寧夏枸杞",
        "荳蔻",
        "茯苓",
        "桂枝",
        "懷菊花",
        "白參",
        "北黃耆",
        "知母",
        "生地黃",
        "骨碎補",
        "薏仁",
        "桑寄生"
    )

    private val herbNameEnglish = arrayOf(
        "英文名稱",
        "Baikal Skullcap Root",
        "RADIX REHMANNIAE",
        "Asiabell Root",
        "Licorice",
        "Two-toothed Achyranthes",
        "Dwarf Lilyturf Root Tuber",
        "Largehead Atractylodes Rhizome",
        "Lobed Kudzuvine Root",
        "White Mulberry Root - bark",
        "Balloonflower Root",
        "Medical Dogwood",
        "Tuber Fleeceflower Root",
        "Red Paeoniae Trichocarpae",
        "Cassia Bark",
        "Chinese Angelica",
        "Szechwan Lovage Rhizome",
        "Safflower",
        "Immature Bitter Orange",
        "Common Jujube",
        "Manchurian Wildginger Herb",
        "Weeping Forsythia Fruit",
        "Common Yam Rhizome",
        "Common Coltsfoot Flower",
        "Dried Ginger",
        "Prepared Common Monkshood Daughter Root",
        "Peach Seed",
        "Tatarian Aster Root",
        "Combined Spicebush Root",
        "Tree Peony Bark",
        "arbary Wolfberry",
        "Nutmeg",
        "Indian Buead Tuckahoe",
        "Cassiabarktree Twig",
        "Florists Dendranthema",
        "Ginseng Root",
        "Mongolian Milkvetch Root",
        "Common Anemarrhena",
        "RADIX REHMANNIAE",
        "Fortune's Drynaria Rhizome",
        "Ma - yuen Jobstears Seed",
        "Chinese Taxillus Herb"
    )
}